version: '3'
services:
  db:
    container_name: db
    build:
      dockerfile: Dockerfiledb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - forum-network
  eureka:
    container_name: eureka
    build: ./eureka-server
    environment:
      EUREKA_URI: http://eureka:8761/eureka/
    ports:
      - "8761:8761"
    restart: always
    depends_on:
      - db
    networks:
      - forum-network
  auth-service:
    container_name: auth-service
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/authservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_URI: http://eureka:8761/eureka/
    depends_on:
      - eureka
    restart: always
    links:
      - db:authservice
    networks:
      - forum-network
  profile-service:
    container_name: profile-service
    build: ./profile-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/profileservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_URI: http://eureka:8761/eureka/
    depends_on:
      - eureka
    restart: always
    links:
      - db:profileservice
    networks:
      - forum-network
  web-service:
    container_name: web-service
    build: ./web-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/webservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_URI: http://eureka:8761/eureka/
    depends_on:
      - eureka
    links:
      - db:webservice
    networks:
      - forum-network
networks:
  forum-network: