version: '3.9'
services:
  db:
    container_name: db
    build:
      dockerfile: Dockerfiledb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  eureka:
    build: ./eureka-server
    expose:
      - "8761"
    networks:
      - forum-network
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/authservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_URI: http://eureka:8761/eureka/
    depends_on:
      - db
    networks:
      - forum-network
  profile-service:
    container_name: profile-service
    build: ./profile-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/profileservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_URI: http://eureka:8761/eureka
    depends_on:
      - db
    restart: always
    networks:
      - forum-network
  web-service:
    container_name: web-service
    build: ./web-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/webservice
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      EUREKA_URI: http://eureka:8761/eureka
    depends_on:
      - db
    networks:
      - forum-network
networks:
  forum-network:
    driver: bridge